config/routes.rb
Rails.application.routes.draw do
  mount ImageUploader::UploadEndpoint => "images/upload"
  root 'home#index'
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {:registrations => "users/registrations",:sessions => "users/sessions" }
  resources :curris
  resources :assignments do
    member do
      # 수정해야함
      get 'submissions'
      get 'submission', as: :destroy_submission, action: :destroy_submission
      post 'submission'
      get 'edit_submission', as: :edit_submission, action: :edit_submission
      # put 'update_submission', as: :update_submission, action: :update_submission
      patch 'update_submission', as: :update_submission, action: :update_submission
    end
  end
  resources :events do
    member do
      post 'ecomment'
    end
  end
  get 'submissions/:id' => 'assignments#show_submission', as: "submission"
  get 'home/index'
  get 'home/wating'
  post 'submission/:id/scomments' => 'assignments#scomments', as: "admin_submission_scomments"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  has_many :submissions, dependent: :destroy
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :set_assignment, only: [:show, :edit, :update, :destroy, :submission,:submissions,:destroy_submission,:submissons,:edit_submission,:update_submission]

  # GET /assignments
  # GET /assignments.json
  def index
    @assignments = Assignment.all
  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show
    if user_signed_in?
      @submission = @assignment.submissions.build(user_id: current_user.id)
      @flag = 0
      if current_user.submissions.exists?(assignment_id: @assignment.id)
        @flag = 1
        @submission = current_user.submissions.find_by(assignment_id: @assignment.id)
      end
    end
  end

  # GET /assignments/new
  def new
    @assignment = Assignment.new
  end

  # GET /assignments/1/edit
  def edit
  end

  # POST /assignments
  # POST /assignments.json
  def create
    @assignment = Assignment.new(assignment_params)

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to @assignment, notice: 'Assignment was successfully created.' }
        format.json { render :show, status: :created, location: @assignment }
      else
        format.html { render :new }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignments/1
  # PATCH/PUT /assignments/1.json
  def update
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to @assignment, notice: 'Assignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @assignment }
      else
        format.html { render :edit }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    @assignment.destroy
    respond_to do |format|
      format.html { redirect_to assignments_url, notice: 'Assignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def destroy_submission
    puts @assignment.submissions
    @assignment.submissions.find_by(user_id: current_user.id).destroy
    respond_to do |format|
      format.html { redirect_to @assignment, notice: '과제가 성공적으로 삭제되었습니다.' }
      format.json { head :no_content }
    end
  end
  
  def submission
    @submission = Submission.new(submission_params)
    # @submission = Submission.new
    @submission.user = current_user
    @submission.assignment = @assignment
    @submission.save
    redirect_back(fallback_location: root_path)
  end
  
  def show_submission
    @submission = Submission.find(params[:id]) 
    @assignment = @submission.assignment
    @flag = 3
    render 'show'
  end
  
  def submissions
    @users = User.where(grade: 6)
    @submissions = @assignment.submissions
  end
  
  def edit_submission
    @submission = @assignment.submissions.find_by(user_id: current_user.id)
    @flag = 2
    render 'show'
  end
  
  def update_submission
    @submission = @assignment.submissions.find_by(user_id: current_user.id)
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @assignment, notice: 'Assignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @assignment }
      else
        format.html { render :edit }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def scomments
    submission = Submission.find params[:id]
    @scomment = submission.scomments.build(scomment_params)
    @scomment.user = current_user
    if @scomment.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end
  
  
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assignment
      @assignment = Assignment.find(params[:id])
    end

    def submission_params
      params.require(:submission).permit(:image,:url,:content)
    end
    
    def scomment_params
      params.require(:scomment).permit(:body)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assignment_params
      params.require(:assignment).permit(:title,:content)
    end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_form.html.erb
<%= form_with(model: assignment, local: true) do |form| %>
  <% if assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
      <% assignment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/assignments/edit.html.erb
<h1>Editing Assignment</h1>

<%= render 'form', assignment: @assignment %>

<%= link_to 'Show', @assignment %> |
<%= link_to 'Back', assignments_path %>

app/views/assignments/index.html.erb
<%= render 'shared/header' %>
<div class="content-wrap">

  <div id="blog" class="inner-content">

    <section id="page-title" class="inner-section ui-menu-color04">
      <div class="container-fluid nopadding">
        <h2 class="font-accident-two-normal2 color05 uppercase" >강의 과제</h2>
        <h4 class="font-accident-two-bold2 color05 uppercase subtitle">동대 멋사 교육팀이 준비중입니다.</h4>
      </div>
    </section>

    <!-- Blog Block -->
    <section class="inner-section " data-section="blog">
      <div class="row masonry-row">
        <div class="container-fluid text-center">
          <div id="posts" class="row popup-container">
            <% @assignments.each do |assignment| %>
              <div class=" col-md-4 col-sm-6">
                <div class="item-wrap curri">
                  <!-- <div class="check red">hot!</div> -->
                  <figure data-animation-origin="right" data-animation-duration="500" data-animation-delay="300" data-animation-distance="0px">
                    <figcaption class="text-center">
                      <div class="post-header">
                        <h5>
                          <a href="#"><%= assignment.title %></a>
                        </h5>
                      </div>
                      <div class="post-entry">
                        <p><%#= assignment.content %></p>
                      </div>
                      <div class="post-meta">
                        <span>by
                          <a href="#!">교육팀</a>,</span>
                        <span><%= assignment.created_at %></span></div>
                      <div class="dividewhite2"></div>
                      <div class="btn-group" role="group"> 
                        <a href="<%= assignment_path(assignment)%>" class="btn btn-info pull-left">보러가기</a>
                        <a href="<%=submissions_assignment_path(assignment)%>" class="btn btn-warning pull-left">훔쳐보기</a>
                      </div>
                      <div class="dividewhite1"></div>
                    </figcaption>
                  </figure>
                </div>
              </div>
            <% end %>

          </div>

        </div>
      </div>

    </div>
  </section>
  <!-- /Blog Block -->
</div>
<%= render "shared/footer" %>

app/views/assignments/new.html.erb
<h1>New Assignment</h1>

<%= render 'form', assignment: @assignment %>

<%= link_to 'Back', assignments_path %>

app/views/assignments/show.html.erb
<%= render "shared/header" %>
<div class="content-wrap">

  <div id="blogpost" class="inner-content">

    <section id="page-title" class="inner-section">
      <div class="container-fluid nopadding">
        <div class="row">
          <div class="col-md-6">
            <h2 class="font-accident-two-normal2 uppercase"><%= @assignment.title %></h2>
          </div>
          <div class="col-md-6 ">
            <a class="btn btn-danger pull-right" href="<%=submissions_assignment_path(@assignment)%>">훔쳐보기</a>
          </div>
        </div>
        <div class="post-meta">
          <span>by
            <a href="#!">교육팀</a>,</span>
          <span><%= @assignment.created_at %></span></div>
        <!-- <div class="post-tag pull-left">
      <!--    <span>-->
      <!--      <a>Branding</a>,</span>-->
      <!--    <span>-->
      <!--      <a>Design</a></span></div>-->
      <!--</div> -->
    </section>

    <!-- Blog Block -->
    <section class="inner-section">

      <div class="container-fluid nopadding">

        <!--<img src="<%#= asset_path 'header.png'%>" class="img-responsive"> -->

        <article class="post">
            <p><%= @assignment.content %></p>

          <div class="dividewhite4"></div>
          <hr>

        </article>

      </div>
      <div class="container-fluid nopadding">
        <% if user_signed_in? %>
          <% if @flag == 3 %>
           <h4 class="font-accident-two-normal uppercase"><%= @submission.user.name %>의 과제</h4>
              <% if @submission.image.nil? %>
                <img src="<%= asset_path 'dgulion.png' %>" class="img-responsive" alt="img11" />
              <% else %>
                <img src="<%= @submission.image.url %>" class="img-responsive" alt="img11" />
              <% end %>
              <article class="post">
                <div class="dividewhite6"></div>
                <p><%= @submission.content %></p>
                <div class="btn-group" role="group"> 
                  <% unless @submission.url.nil? %>
                    <a href="<%=@submission.url %>" class="btn btn-primary pull-left" target="_blank">url</a>
                  <% end %>
                </div>
                 
                <div class="dividewhite4"></div>
                <hr>
              </article>
              <div id="comments">
                <h4 class="font-accident-one-light uppercase"><%= @submission.scomments.count%> comments:</h4>
                <!--<div class="dividewhite4"></div>-->
                <ul class="media-list">
                <% @submission.scomments.each do |c| %>
                  <li class="media">
                     <div class="media-left">
                        <a href="#">
                          <% if c.user.image.nil? %>
                            <img src="<%= asset_path 'dgulion.png' %>" class="media-object" alt="img11" />
                          <% else %>
                            <img src="<%= c.user.image.url %>" class="media-object" alt="img11" />
                          <% end %>
                        </a>
                     </div>
                     <div class="media-body">
                        <div class="post-data">
                           <div class="post-date"><%= c.updated_at %></div>
                           <div class="post-author"><a href="#"><%= c.user.name %></a></div>
                        </div>
                        <p><%= c.body %></p>
                        <!--<p><a href="#" class="btn btn-gr btn-xs">Log In to Reply</a></p>-->
                     </div>
                  </li>
                <% end %>
               </ul>

              </div>
          <% elsif @flag == 0 %>
            <h4 class="font-accident-two-normal uppercase">과제 제출</h4>
            <%= form_for(@submission, url: submission_assignment_path) do |f| %>
              <div class="row">
                <div class="col-md-6">
                  <p>
                    <label for="">이미지</label>
                    <%= f.file_field :image %>
                  </p>
                </div>
                <div class="col-md-6">
                  <p>
                    <label for="">url</label>
                    <%= f.url_field :url, placeholder: "url을 적어주세요" %>
                  </p>
                </div>
                <div class="col-md-12">
                  <p>
                    <label>내용</label>
                    <%= f.text_area :content, placeholder: "과제에 대한 설명을 적어주세요" %>
                  </p>
                </div>
              </div>
              <div class="dividewhite2"></div>
              <p><%= f.submit "과제 제출", class: "btn btn-lg btn-darker" %></p>
            <% end %>
          <% elsif @flag == 1 %>
              <h4 class="font-accident-two-normal uppercase">나의 과제</h4>
              <% if @submission.image.nil? %>
                <img src="<%= asset_path 'dgulion.png' %>" class="img-responsive" alt="img11" />
              <% else %>
                <img src="<%= @submission.image.url %>" class="img-responsive" alt="img11" />
              <% end %>
              <article class="post">
                <div class="dividewhite6"></div>
                <p><%= @submission.content %></p>
                <div class="btn-group" role="group"> 
                  <% unless @submission.url.nil? %>
                    <a href="<%=@submission.url %>" class="btn btn-primary pull-left" target="_blank">url</a>
                  <% end %>
                  <%= link_to "삭제", destroy_submission_assignment_path, class: "btn btn-danger pull-left" %>
                  <a href="<%= edit_submission_assignment_path %>" class="btn btn-warning pull-left">수정</a>
                </div>
                 
                <div class="dividewhite4"></div>
                <hr>
              </article>
              <div id="comments">
                <h4 class="font-accident-one-light uppercase"><%= @submission.scomments.count%> comments:</h4>
                <!--<div class="dividewhite4"></div>-->
                <ul class="media-list">
                <% @submission.scomments.each do |c| %>
                  <li class="media">
                     <div class="media-left">
                        <a href="#">
                          <% if c.user.image.nil? %>
                            <img src="<%= asset_path 'dgulion.png' %>" class="media-object" alt="img11" />
                          <% else %>
                            <img src="<%= c.user.image.url %>" class="media-object" alt="img11" />
                          <% end %>
                        </a>
                     </div>
                     <div class="media-body">
                        <div class="post-data">
                           <div class="post-date"><%= c.updated_at %></div>
                           <div class="post-author"><a href="#"><%= c.user.name %></a></div>
                        </div>
                        <p><%= c.body %></p>
                        <!--<p><a href="#" class="btn btn-gr btn-xs">Log In to Reply</a></p>-->
                     </div>
                  </li>
                <% end %>
               </ul>

              </div>
               
              <% elsif @flag == 2 %>
                <h4 class="font-accident-two-normal uppercase">과제 수정</h4>
                  <%= form_for(@submission, url: update_submission_assignment_path) do |f| %>
                    <div class="row">
                      <div class="col-md-6">
                        <p>
                          <label for="">이미지</label>
                          <%= f.file_field :image %>
                        </p>
                      </div>
                      <div class="col-md-6">
                        <p>
                          <label for="">url</label>
                          <%= f.text_field :url, placeholder: "url을 적어주세요" %>
                        </p>
                      </div>
                      <div class="col-md-12">
                        <label>내용</label>
                        <%= f.text_area :content, placeholder: "과제에 대한 설명을 적어주세요" %>
                      </div>
                    </div>
                    <div class="dividewhite2"></div>
                    <p><%= f.submit "과제 제출", class: "btn btn-lg btn-darker" %></p>
                  <% end %>
              <% else %>
          <% end %>
        <% else %>
          <div class="row">
            <div class="col-md-12">
              <a href="<%= new_user_session_path%>" class="btn btn-lg btn-default pull-right">로그인 하세요</a>
            </div>
          </div>
        <% end %>
        <!-- <a href="" class="btn btn-lg btn-default pull-left">뒤로 가기</a>
        <a href="" class="btn btn-lg btn-default pull-right">과제 제출</a> -->
      </div>
    </section>
    <!-- /Blog Block -->

  </div>

</div>

app/views/assignments/submissions.html.erb
<%= render "shared/header" %>
<div class="content-wrap">
    <div id="blog" class="inner-content">
        <section class="inner-section " data-section="blog">
          <div class="row masonry-row">
            <div class="container-fluid text-center">
              <div id="posts" class="row popup-container">
                <% @users.each do |user| %>
                  <div class=" col-md-4 col-sm-6">
                    <div class="item-wrap curri">
                      <!-- <div class="check red">hot!</div> -->
                      <figure >
                        <figcaption class="text-center">
                          <div class="post-header">
                            <h3 class="text-black">
                              <%= user.name %>
                            </h3>
                          </div>
                          <% submission = user.submissions.find_by(assignment: @assignment) %>
                          <% if submission.nil? %>
                              <img src="<%= asset_path 'no_assignment.png'%>" class="img-responsive curri-img" alt="img11" />
                              <div class="post-entry">
                                <p><%#= submission.content %></p>
                              </div>
                              <!--<div class="post-meta">-->
                              <!--  <span>by-->
                              <!--    <a href="#!">교육팀</a>,</span>-->
                              <!--  <span>언젠가는 내겠지요.</span></div>-->
                          <% else %>
                              <% if submission.image.nil? %>
                                <img src="<%= asset_path 'dgulion.png' %>" class="img-responsive" alt="img11" />
                              <% else %>
                                <img src="<%= submission.image.url %>" class="img-responsive" alt="img11" />
                              <% end %>
                              
                              <div class="post-entry">
                                <p><%= submission.content %></p>
                              </div>
                              <div class="post-meta">
                                <span><%= submission.created_at%></span></div>
                              <div class="dividewhite2"></div>
                              <div class="btn-group" role="group"> 
                                <a href="<%= submission.url%>" class="btn btn-primary pull-left" target="_blank">url</a>
                                <%= link_to "보러가기", submission_path(submission), class: "btn btn-danger pull-left" %>
                                <% if user_signed_in? && current_user.has_role?(:admin) %>
                                  <a href="<%= admin_submission_path(submission) %>" target="_blank" class="btn btn-warning pull-left">어드민</a>
                                <% end %>
                              </div>
                              <div class="dividewhite1"></div>
                          <% end %>
                          
                        </figcaption>
                      </figure>
                    </div>
                  </div>
                <% end %>
    
              </div>
    
            </div>
          </div>
    
        </div>
      </section>

    </div>
</div>
<%= render "shared/footer" %>