config/routes.rb
Rails.application.routes.draw do
  mount ImageUploader::UploadEndpoint => "images/upload"
  root 'home#index'
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {:registrations => "users/registrations",:sessions => "users/sessions" }
  resources :curris
  resources :assignments do
    member do
      # 수정해야함
      get 'submissions'
      get 'submission', as: :destroy_submission, action: :destroy_submission
      post 'submission'
      get 'edit_submission', as: :edit_submission, action: :edit_submission
      # put 'update_submission', as: :update_submission, action: :update_submission
      patch 'update_submission', as: :update_submission, action: :update_submission
    end
  end
  resources :events do
    member do
      post 'ecomment'
    end
  end
  get 'submissions/:id' => 'assignments#show_submission', as: "submission"
  get 'home/index'
  get 'home/wating'
  post 'submission/:id/scomments' => 'assignments#scomments', as: "admin_submission_scomments"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/curri.rb
class Curri < ApplicationRecord
  has_many :courses
end

app/controllers/curris_controller.rb
class CurrisController < ApplicationController
  before_action :set_curri, only: [:show, :edit, :update, :destroy]

  # GET /curris
  # GET /curris.json
  def index
    @curris = Curri.all
  end

  # GET /curris/1
  # GET /curris/1.json
  def show
  end

  # GET /curris/new
  def new
    @curri = Curri.new
  end

  # GET /curris/1/edit
  def edit
  end

  # POST /curris
  # POST /curris.json
  def create
    @curri = Curri.new(curri_params)

    respond_to do |format|
      if @curri.save
        format.html { redirect_to @curri, notice: 'Curri was successfully created.' }
        format.json { render :show, status: :created, location: @curri }
      else
        format.html { render :new }
        format.json { render json: @curri.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /curris/1
  # PATCH/PUT /curris/1.json
  def update
    respond_to do |format|
      if @curri.update(curri_params)
        format.html { redirect_to @curri, notice: 'Curri was successfully updated.' }
        format.json { render :show, status: :ok, location: @curri }
      else
        format.html { render :edit }
        format.json { render json: @curri.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /curris/1
  # DELETE /curris/1.json
  def destroy
    @curri.destroy
    respond_to do |format|
      format.html { redirect_to curris_url, notice: 'Curri was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curri
      @curri = Curri.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def curri_params
      params.require(:curri).permit(:title,:image,:desc)
    end
end

app/helpers/curris_helper.rb
module CurrisHelper
end

app/views/curris/_form.html.erb
<%= form_with(model: curri, local: true) do |form| %>
  <% if curri.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(curri.errors.count, "error") %> prohibited this curri from being saved:</h2>

      <ul>
      <% curri.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/curris/edit.html.erb
<h1>Editing Curri</h1>

<%= render 'form', curri: @curri %>

<%= link_to 'Show', @curri %> |
<%= link_to 'Back', curris_path %>

app/views/curris/index.html.erb
<%= render 'shared/header' %>
<div class="content-wrap">

  <div id="blog" class="inner-content">

    <section id="page-title" class="inner-section ui-menu-color03">
      <div class="container-fluid nopadding">
        <h2 class="font-accident-two-normal2 color01 uppercase" >강의 커리큘럼</h2>
        <h4 class="font-accident-two-bold2 color01 uppercase subtitle" >동대 멋사 교육팀이 준비중입니다.</h4>
      </div>
    </section>

    <!-- Blog Block -->
    <section class="inner-section " data-section="blog">
      <div class="row masonry-row">

        <div class="container-fluid text-center">

          <div id="posts" class="row popup-container">
            <% @curris.each do |curri| %>
              <div class=" col-md-4 col-sm-6">
                <div class="item-wrap curri">
                  <!-- <div class="check red">hot!</div> -->
                  <figure data-animation-origin="right" data-animation-duration="500" data-animation-delay="300" data-animation-distance="0px">
                    <img src="<%= image curri %>" class="img-responsive curri-img" alt="img11" />
                    <figcaption class="text-center">
                      <div class="post-header">
                        <h5>
                          <a href="#"><%= curri.title %></a>
                        </h5>
                      </div>
                      <div class="post-entry">
                        <p><%= curri.desc %></p>
                      </div>
                      <div class="post-meta">
                        <span>by
                          <a href="#!">교육팀</a>,</span>
                        <span><%= curri.created_at %></span></div>
                      <!-- <div class="post-tag pull-left">
                        <span>
                          <a href="#branding" data-filter=".branding">Branding</a>,</span>
                        <span>
                          <a href="#design" data-filter=".design">Design</a>
                        </span>
                      </div> -->
                      <div class="dividewhite2"></div>
                      <div class="post-more-link pull-center btn btn-lg btn-lgr-str">
                        <%= link_to '보러가기', curri %>
                      </div>
                      <div class="dividewhite1"></div>
                    </figcaption>
                  </figure>
                </div>
              </div>
            <% end %>

          </div>

        </div>
      </div>

    </div>
  </section>
  <!-- /Blog Block -->
</div>

<%#= link_to 'Edit', edit_curri_path(curri) %>
<%#= link_to 'Destroy', curri, method: :delete, data: { confirm: 'Are you sure?' } %>

<%#= link_to 'New Curri', new_curri_path %>

app/views/curris/new.html.erb
<h1>New Curri</h1>

<%= render 'form', curri: @curri %>

<%= link_to 'Back', curris_path %>

app/views/curris/show.html.erb
<%= render 'shared/header' %>
<!-- <p id="notice"><%= notice %></p> -->

<!-- Container -->
<div class="content-wrap">

  <div id="resume" class="inner-content">

    <section id="page-title" class="inner-section ui-menu-color03">
      <div class="container-fluid nopadding">
        <h2 class="font-accident-two-normal color01 uppercase" data-animation-origin="right" data-animation-duration="400" data-animation-delay="100" data-animation-distance="50px">강의 커리큘럼</h2>
        <h5 class="font-accident-two-bold color01 uppercase subtitle" data-animation-origin="right" data-animation-duration="400" data-animation-delay="200" data-animation-distance="50px">동대 멋사 교육팀이 준비하고 있습니다.</h5>
      </div>
    </section>
    <!-- Timeline Block -->
    <section id="timeline" class="light inner-section">

      <div class="container-fluid nopadding">

        <div class="text-center" data-animation-origin="top" data-animation-duration="400" data-animation-delay="400" data-animation-distance="30px">
          <div class="dividewhite4"></div>
          <h3 class="font-accident-two-normal uppercase"><%= @curri.title %></h3>
          <h5 class="font-accident-two-bold uppercase subtitle">write by 동대 멋사</h5>
        </div>

        <div class="dividewhite4"></div>

        <ul class="timeline-vert timeline">
          <% @curri.courses.each do |course| %>
            <li>
              <div class="timeline-badge primary">
                <i class="flaticon-clocks18"></i>
              </div>
              <div class="timeline-panel" data-animation-origin="left" data-animation-duration="400" data-animation-delay="400" data-animation-distance="25px">
                <p class="timeline-time fontcolor-invert"><%= course.created_at %></p>
                <div class="timeline-photo">
                  <img class="timeline-img" src="/image/logo.png" alt="">
                </div>
                <div class="timeline-heading">
                  <h4 class="font-accident-two-normal uppercase"><%= course.title %></h4>
                  <h6 class="uppercase"><%= course.user.name %></h6>
                  <p>
                    <%= course.content %>
                  </p>
                </div>
              </div>
            </li>
          <% end %>
          <li>
            <div class="timeline-badge primary">
              <i class="flaticon-clocks18"></i>
            </div>
            <div class="timeline-panel" data-animation-origin="left" data-animation-duration="400" data-animation-delay="400" data-animation-distance="25px">
              <p class="timeline-time fontcolor-invert">Aug 2010 - Nov 2012</p>
              <div class="timeline-photo timeline-james-01"></div>
              <div class="timeline-heading">
                <h4 class="font-accident-two-normal uppercase">Bluepixel LLC, London</h4>
                <h6 class="uppercase">Junior Designer</h6>
                <p>
                  There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour
                </p>
              </div>
            </div>
          </li>
          <li>
            <div class="timeline-badge primary">
              <i class="flaticon-clocks18"></i>
            </div>
            <div class="timeline-panel" data-animation-origin="left" data-animation-duration="400" data-animation-delay="400" data-animation-distance="25px">
              <p class="timeline-time fontcolor-invert">Aug 2010 - Nov 2012</p>
              <div class="timeline-photo timeline-james-01"></div>
              <div class="timeline-heading">
                <h4 class="font-accident-two-normal uppercase">Bluepixel LLC, London</h4>
                <h6 class="uppercase">Junior Designer</h6>
                <p>
                  There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour
                </p>
              </div>
            </div>
          </li>
          <li class="timeline-inverted">
            <div class="timeline-badge success">
              <i class="flaticon-graduation61"></i>
            </div>
            <div class="timeline-panel" data-animation-origin="right" data-animation-duration="400" data-animation-delay="400" data-animation-distance="25px">
              <p class="timeline-time fontcolor-invert">March 2013 - Jan 2014</p>
              <div class="timeline-photo timeline-james-02"></div>
              <div class="timeline-heading">
                <h4 class="font-accident-two-normal uppercase">Rocket Media, Berlin</h4>
                <h6 class="uppercase">Senior Designer</h6>
                <p>
                  There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour
                </p>
              </div>
            </div>
          </li>
          <li>
            <div class="timeline-badge danger">
              <i class="flaticon-pens15"></i>
            </div>
            <div class="timeline-panel" data-animation-origin="left" data-animation-duration="400" data-animation-delay="400" data-animation-distance="25px">
              <p class="timeline-time fontcolor-invert">Jul 2014 - Sep 2015</p>
              <div class="timeline-photo timeline-james-03"></div>
              <div class="timeline-heading">
                <h4 class="font-accident-two-normal uppercase">Digital Frog, Wien</h4>
                <h6 class="uppercase">Art Director</h6>
                <p>
                  There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour
                </p>
              </div>
            </div>
          </li>
          <li class="timeline-inverted info">
            <div class="timeline-badge warning">
              <i class="flaticon-profile5"></i>
            </div>
            <div class="timeline-panel" data-animation-origin="right" data-animation-duration="400" data-animation-delay="400" data-animation-distance="25px">
              <p class="timeline-time fontcolor-invert">Sep 2015 - ...</p>
              <div class="timeline-photo timeline-james-04"></div>
              <div class="timeline-heading">
                <h4 class="font-accident-two-normal uppercase">Melted Digital, Paris</h4>
                <h6 class="uppercase">Head of UX Department</h6>
                <p>
                  There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour
                </p>
              </div>
            </div>
          </li>

        </ul>

        <div class="text-center">
          <a href="#!" class="btn btn-darker" data-animation-origin="bottom" data-animation-duration="300" data-animation-delay="600" data-animation-distance="35px">Learn More</a>
        </div>

        <div class="dividewhite6"></div>

      </div>

    </section>
    <!-- /Timeline Block -->

  </div>

</div>

<%= link_to 'Edit', edit_curri_path(@curri) %>
|
<%= link_to 'Back', curris_path %>