config/routes.rb
Rails.application.routes.draw do
  mount ImageUploader::UploadEndpoint => "images/upload"
  root 'home#index'
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {:registrations => "users/registrations",:sessions => "users/sessions" }
  resources :curris
  resources :assignments do
    member do
      # 수정해야함
      get 'submissions'
      get 'submission', as: :destroy_submission, action: :destroy_submission
      post 'submission'
      get 'edit_submission', as: :edit_submission, action: :edit_submission
      # put 'update_submission', as: :update_submission, action: :update_submission
      patch 'update_submission', as: :update_submission, action: :update_submission
    end
  end
  resources :events do
    member do
      post 'ecomment'
    end
  end
  get 'submissions/:id' => 'assignments#show_submission', as: "submission"
  get 'home/index'
  get 'home/wating'
  post 'submission/:id/scomments' => 'assignments#scomments', as: "admin_submission_scomments"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    else
      cannot :manage, ActiveAdmin::Page
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  has_many :submissions, dependent: :destroy
end

app/models/course.rb
class Course < ApplicationRecord
  acts_as_paranoid
  belongs_to :curri
  belongs_to :user
end

app/models/curri.rb
class Curri < ApplicationRecord
  has_many :courses
end

app/models/ecomment.rb
class Ecomment < ApplicationRecord
  belongs_to :event


  def self.public_comments
    self.where(secret: [nil,false])
  end

  def self.secret_comments
    self.where(secret: true)
  end
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :ecomments
  include ImageUploader[:image]
end

app/models/image_uploader.rb
class ImageUploader < Shrine
    
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/scomment.rb
class Scomment < ApplicationRecord
  belongs_to :submission
  belongs_to :user
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :assignment
  belongs_to :user
  has_many :scomments, dependent: :destroy
  # has_many
  include ImageUploader[:image]
  before_save :set_title
  
  def set_title
    self.title = self.assignment.title.to_s+"_"+self.user.name.to_s
  end
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  include ImageUploader[:image]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_update :assign_default_role
  scope :admin, -> {with_role :admin}
  scope :default, -> {with_role :default}
  def assign_default_role
    self.add_role(:default) if self.roles.blank?
  end
  has_many :submissions
end

app/controllers/curris_controller.rb
class CurrisController < ApplicationController
  before_action :set_curri, only: [:show, :edit, :update, :destroy]

  # GET /curris
  # GET /curris.json
  def index
    @curris = Curri.all
  end

  # GET /curris/1
  # GET /curris/1.json
  def show
  end

  # GET /curris/new
  def new
    @curri = Curri.new
  end

  # GET /curris/1/edit
  def edit
  end

  # POST /curris
  # POST /curris.json
  def create
    @curri = Curri.new(curri_params)

    respond_to do |format|
      if @curri.save
        format.html { redirect_to @curri, notice: 'Curri was successfully created.' }
        format.json { render :show, status: :created, location: @curri }
      else
        format.html { render :new }
        format.json { render json: @curri.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /curris/1
  # PATCH/PUT /curris/1.json
  def update
    respond_to do |format|
      if @curri.update(curri_params)
        format.html { redirect_to @curri, notice: 'Curri was successfully updated.' }
        format.json { render :show, status: :ok, location: @curri }
      else
        format.html { render :edit }
        format.json { render json: @curri.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /curris/1
  # DELETE /curris/1.json
  def destroy
    @curri.destroy
    respond_to do |format|
      format.html { redirect_to curris_url, notice: 'Curri was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curri
      @curri = Curri.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def curri_params
      params.require(:curri).permit(:title,:image,:desc)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def wating
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def image obj
    obj.image? ? obj.image.url : "/image/logo.png"
  end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/curris_helper.rb
module CurrisHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-90057623-3"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
    
      gtag('config', 'UA-90057623-3');
    </script>
    <title>동국대 멋쟁이사자처럼</title>
    <%= csrf_meta_tags %>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="description" content="동국대 멋사 official web site">
    <meta name="keywords" content="dgu lion likelion">
    <meta name="author" content="wonno">
    
    <%= favicon_link_tag %>
    <!-- Preloader -->
    <!-- <link href="/assets/custom/2.2.0/css/preloader.css" property='stylesheet' rel="stylesheet" type="text/css" media="screen"/> -->
    
    <!-- CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" media="screen">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" property='stylesheet' rel="stylesheet" type="text/css" media="screen"/>
    <link href="/assets/vendor/flaticons/flaticon.min.css?v=29022016" property='stylesheet' rel="stylesheet" type="text/css" media="screen"/>
    <link href="/assets/vendor/hover/css/hover-min.css?v=2.0.2" property='stylesheet' rel="stylesheet" type="text/css" media="screen"/>
    <link href="/assets/vendor/mfp/css/magnific-popup.min.css?v=1.1.0" property='stylesheet' rel="stylesheet" type="text/css" media="screen"/>
    <link href="/assets/vendor/owl-carousel/assets/owl.carousel.min.css?v=2.1.0" property='stylesheet' rel="stylesheet" type="text/css" media="screen"/>

    <!-- Custom styles -->
    <link href="/assets/custom/2.2.0/css/style.css" property='stylesheet' rel="stylesheet" type="text/css" media="screen"/>
    <link href="/assets/custom/2.2.0/css/layouts/james.css" property='stylesheet' rel="stylesheet" type="text/css" media="screen"/>
    <link href="/assets/custom/2.2.0/css/colors/light.css" id="color-styles" property='stylesheet' rel="stylesheet" type="text/css" media="screen"/>
  </head>

  <body id="james" class="boxed">
    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>
    <%= yield %>


    <!-- JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://npmcdn.com/imagesloaded@4.1/imagesloaded.pkgd.min.js"></script>
    <script src="https://unpkg.com/isotope-layout@3.0/dist/isotope.pkgd.min.js"></script>
    <script src="https://unpkg.com/scrollreveal@3.3.2/dist/scrollreveal.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/velocity/1.2.3/velocity.min.js"></script> 

    <script src="/assets/vendor/mfp/js/jquery.magnific-popup.min.js?v=1.1.0" type="text/javascript"></script>
    <script src="/assets/vendor/progressbar/progressbar.min.js?v=1.0.1" type="text/javascript"></script>
    <script src="/assets/vendor/anicounter/jquery.counterup.min.js?v=1.0" type="text/javascript"></script>
     <!--<script src="/assets/vendor/pjax/jquery.pjax.min.js?v=1.9.6" type="text/javascript"></script> -->
    <script src="/assets/vendor/owl-carousel/owl.carousel.min.js?v=2.1.0" type="text/javascript"></script>
    <script src="/assets/vendor/headlines/headlines.min.js?v=1.0" type="text/javascript"></script>

    <!-- Custom scripts -->
     <!--<script src="/assets/custom/2.2.0/js/animation.js" type="text/javascript"></script> -->
    <script src="/assets/custom/2.2.0/js/custom.js" type="text/javascript"></script>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="padding-50 dark ui-bg-color01" data-animation-origin="top" data-animation-duration="500" data-animation-delay="800" data-animation-distance="50px">
  <div class="container-fluid nopadding">
    <div class="row">
      <div class="col-md-12 copyrights text-right">
        <p>© 2018 DGULION.</p>
      </div>
    </div>
  </div>
</footer>
<!-- Back to Top -->
<div id="back-top"></div>
<!-- /Back to Top -->

app/views/shared/_header.html.erb
<div id="preloader"></div>
<header>
  <section id="top-navigation" class="container-fluid nopadding">
    <div class="row nopadding ident ui-bg-color01">
      <!-- Photo -->
      <a href="/">
        <div class="col-md-5 vc-photo photo-likelion">&nbsp;</div>
      </a>
      <!-- /Photo -->
      <div class="col-md-7 vc-name nopadding">
        <!-- Name-Position -->
        <div class="row nopadding name">
          <div class="col-md-10 name-title">
            <h1 class="font-accident-two-normal3" >동국대 멋쟁이사자처럼</h1>
          </div>
          <div class="col-md-2 nopadding name-pdf">
            <% if user_signed_in?%>
              <a href="<%= destroy_user_session_path %>" class="hvr-sweep-to-right">
                <i class="flaticon-profile5" title="로그아웃"></i>
                <span class="color25">로그아웃</span>
              </a>
            <% else %>
              <a href="<%= new_user_session_path %>" class="hvr-sweep-to-right">
                <i class="flaticon-profile5" title="로그인"></i>
                <span class="color25">로그인</span>
              </a>
            <% end %>

          </div>
        </div>
        <div class="row nopadding position">
          <div class="col-md-10 position-title">
            <section class="cd-intro">
              <h2 class="cd-headline clip is-full-width font-accident-two-light">
                <span class="cd-words-wrapper">
                  <b class="is-visible"><font class="color-red">D</font>esi<font class="color-red">G</font>n yo<font class="color-red">U</font>r <font class="color-red">LI</font>fe <font class="color-red">ON</font> yourself</b>
                  <b class="color-red">DGULION</b>
                </span>
              </h2>
            </section>

          </div>
          <div class="col-md-2 nopadding pdf">
            <a href="https://www.facebook.com/DGUlion/" class="hvr-sweep-to-right" target="_blank">
              <i class="fa fa-facebook" title="My Behance Portfolio"></i>
              <span class="color25">동대멋사페북</span>
            </a>
          </div>
        </div>
        <!-- /Name-Position -->

        <!-- Main Navigation -->

        <ul id="nav" class="row nopadding cd-side-navigation">
          <li class="col-xs-4 col-sm-2 nopadding menuitem ui-menu-color01">
            <a href="<%= root_path %>" class="hvr-sweep-to-bottom">
              <i class="flaticon-insignia"></i>
              <span>홈</span></a>
          </li>
          <li class="col-xs-4 col-sm-2 nopadding menuitem ui-menu-color02">
            <a href="<%= events_path %>" class="hvr-sweep-to-bottom">
              <i class="flaticon-graduation61"></i>
              <span>대나무숲</span></a>
          </li>
          <li class="col-xs-4 col-sm-2 nopadding menuitem ui-menu-color03">
            <a href="<%= curris_path %>" class="hvr-sweep-to-bottom">
              <i class="flaticon-book-bag2"></i>
              <span>강의</span></a>
          </li>
          <li class="col-xs-4 col-sm-2 nopadding menuitem ui-menu-color04">
            <a href="<%= assignments_path %>" class="hvr-sweep-to-bottom">
              <i class="flaticon-placeholders4"></i>
              <span>과제</span></a>
          </li>
          <li class="col-xs-4 col-sm-2 nopadding menuitem ui-menu-color05">
            <a href="<%= home_wating_path %>" class="hvr-sweep-to-bottom">
              <i class="flaticon-earphones18"></i>
              <span>활동</span></a>
          </li>
          <li class="col-xs-4 col-sm-2 nopadding menuitem ui-menu-color06">
            <a href="<%= home_wating_path %>" class="hvr-sweep-to-bottom">
              <i class="flaticon-pens15"></i>
              <span>other</span></a>
          </li>
        </ul>

        <!-- /Main Navigation -->

      </div>
    </div>
  </section>

</header>