config/routes.rb
Rails.application.routes.draw do
  mount ImageUploader::UploadEndpoint => "images/upload"
  root 'home#index'
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {:registrations => "users/registrations",:sessions => "users/sessions" }
  resources :curris
  resources :assignments do
    member do
      # 수정해야함
      get 'submissions'
      get 'submission', as: :destroy_submission, action: :destroy_submission
      post 'submission'
      get 'edit_submission', as: :edit_submission, action: :edit_submission
      # put 'update_submission', as: :update_submission, action: :update_submission
      patch 'update_submission', as: :update_submission, action: :update_submission
    end
  end
  resources :events do
    member do
      post 'ecomment'
    end
  end
  get 'submissions/:id' => 'assignments#show_submission', as: "submission"
  get 'home/index'
  get 'home/wating'
  post 'submission/:id/scomments' => 'assignments#scomments', as: "admin_submission_scomments"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :ecomments
  include ImageUploader[:image]
end

app/controllers/events_controller.rb
require 'faker'
Faker::Config.locale = 'ko'
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :ecomment]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @ecomment = @event.ecomments.build
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  def ecomment
    @ecomment = Ecomment.new(ecomment_params)
    @ecomment.event = @event
    @ecomment.save
    redirect_back(fallback_location: root_path)
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.fetch(:event, {})
    end

    def ecomment_params
      params.require(:ecomment).permit(:body,:secret)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<%= render 'shared/header' %>
<div class="content-wrap">

  <div id="blog" class="inner-content">

    <section id="page-title" class="inner-section ui-menu-color02">
      <div class="container-fluid nopadding">
        <h2 class="font-accident-two-normal2 color05 uppercase" >동대 멋사 대나무숲</h2>
        <h4 class="font-accident-two-bold2 color05 uppercase subtitle">동대 멋사 운영진이 열일중입니다.</h4>
      </div>
    </section>

    <!-- Blog Block -->
    <section class="inner-section " data-section="blog">
      <div class="row masonry-row">
        <div class="container-fluid text-center">
          <div id="posts" class="row popup-container">
            <% @events.each do |event| %>
              <div class=" col-md-4 col-sm-6">
                <div class="item-wrap curri">
                  <!-- <div class="check red">hot!</div> -->
                  <figure data-animation-origin="right" data-animation-duration="500" data-animation-delay="300" data-animation-distance="0px">
                    <figcaption class="text-center">
                      <div class="post-header">
                        <h5>
                          <a href="#"><%= event.title %></a>
                        </h5>
                      </div>
                      <div class="post-entry">
                        <%#= event.content %>
                      </div>
                      <!-- <div class="post-meta">
                        <span>by
                          <a href="#!">교육팀</a>,</span>
                        <span><%#= event.created_at %></span></div> -->
                      <!-- <div class="dividewhite2"></div> -->
                      <div class="btn-group" role="group">
                        <a href="<%= event_path(event)%>" class="btn btn-info pull-left">한 마디!</a>                      </div>
                      <div class="dividewhite1"></div>
                    </figcaption>
                  </figure>
                </div>
              </div>
            <% end %>

          </div>

        </div>
      </div>

    </div>
  </section>
  <!-- /Blog Block -->
</div>
<%= render "shared/footer" %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<%= render "shared/header" %>
<div class="content-wrap">

  <div id="blogpost" class="inner-content">

    <section id="page-title" class="inner-section">
      <div class="container-fluid nopadding">
        <div class="row">
          <div class="col-md-6">
            <h2 class="font-accident-two-normal2 uppercase"><%= @event.title %></h2>
          </div>
          <% if false %>
          <div class="col-md-6 ">
            <a class="btn btn-danger pull-right" href="<%=submissions_assignment_path(@assignment)%>">훔쳐보기</a>
          </div>
          <% end %>
        </div>
        <div class="post-meta">
          <span>by
            <a href="#!">교육팀</a>,</span>
          <span><%= @event.created_at %></span></div>
    </section>

    <!-- Blog Block -->
    <section class="inner-section">

      <div class="container-fluid nopadding">
        <article class="post">
            <%= @event.content.html_safe %>
          <div class="dividewhite4"></div>
          <hr>

        </article>
        <div id="comments">
          <div class="container-fluid nopadding">
            <% if user_signed_in? %>
                <%= form_for(@ecomment, url: ecomment_event_path) do |f| %>
                  <div class="row">
                    <div class="col-md-12">
                      <p>
                        <label>내용</label>
                        <%= f.text_area :body, placeholder: "여러분의 생각을 적어주세요." %>
                      </p>
                    </div>


                  </div>
                  <div class="dividewhite2"></div>
                  <div class="row">
                    <div class="col-md-2 col-xs-6">
                      <div class="row">
                        <div class="col-md-2 col-xs-4">
                          <%= f.check_box :secret ,class: "pull-right" %>
                        </div>
                        <div class="col-md-10 col-xs-8">
                          <label for="ecomment_secret">비밀글</label>
                        </div>
                      </div>
                    </div>
                    <div class="col-md-10 col-xs-6">
                      <%= f.submit "제출", class: "btn btn-darker" %>
                    </div>
                  </div>
                  <p></p>
                <% end %>
            <% else %>
              <div class="row">
                <div class="col-md-12 col-xs-6">
                  <a href="<%= new_user_session_path%>" class="btn btn-lg btn-default pull-right">로그인 하세요</a>
                </div>
              </div>
            <% end %>
            <!-- <a href="" class="btn btn-lg btn-default pull-left">뒤로 가기</a>
            <a href="" class="btn btn-lg btn-default pull-right">과제 제출</a> -->
          </div>
          <div class="dividewhite2"></div>
          <hr>
          <div class="row">
            <div class="col-md-6">
              <h4 class="font-accident-one-light uppercase"><%= @event.ecomments.public_comments.count%> 개의 공개글
                <% if user_signed_in? && current_user.has_role?(:admin) %>
                  (비밀글 : <%= @event.ecomments.secret_comments.count %>)
                <% end %>
              </h4>
            </div>
            <div class="col-md-6 pull-right">
              <% if user_signed_in? && current_user.has_role?(:admin) %>
                <%= link_to '비밀 댓글 확인', admin_event_path(@event), class: "btn btn-info pull-right",target: "_blank" %>
              <% end %>
            </div>
          </div>


          <!--<div class="dividewhite4"></div>-->
          <ul class="media-list">
          <% @event.ecomments.public_comments.each_with_index do |c,i| %>
          <% unless i == @event.ecomments.count %>
            <li class="media">
               <div class="media-left">
                  <a href="#">
                    <img src="<%= asset_path 'dgulion.png' %>" class="media-object" alt="img11" />
                  </a>
               </div>
               <div class="media-body">
                  <div class="post-data">
                     <div class="post-date"><%=  time_ago_in_words c.updated_at %></div>
                     <div class="post-author"><a href="#"><%= Faker::Name.name %></a></div>
                  </div>
                  <p><%= c.body %></p>
               </div>
            </li>
          <% end %>
          <% end %>
         </ul>

        </div>
      </div>

    </section>
    <!-- /Blog Block -->

  </div>

</div>
<%= render 'shared/footer' %>